name: Release

on:
  push:
    branches:
      - "main"

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release-to-github:
    runs-on: ubuntu-latest
    name: "Create a new release & update changelog using semantic-release"
    steps:
      - uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: 22
          registry-url: https://npm.pkg.github.com
          scope: "@blastorg"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run tsc
      - run: pnpm run prettier
      - run: pnpm run lint
      - run: pnpm run build
      - name: semantic-release
        run: pnpm dlx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  release-to-npm:
    runs-on: ubuntu-latest
    name: "Release to NPM"
    steps:
      - uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          scope: "@blastorg"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run tsc
      - run: pnpm run prettier
      - run: pnpm run lint
      - run: pnpm run build
      - name: semantic-release
        run: pnpm dlx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_READWRITE_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
